spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springtest
    username: root
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    org.hibernate.SQL: DEBUG